USE customer_behaviour;
SELECT * FROM mytable LIMIT 5;

-- Total Revenue generated by male vs. female customers
SELECT gender, SUM(purchase_amount) as Revenue 
FROM mytable GROUP BY gender;

-- Which customers used a discount but still spent more than the average purchase amount?
SELECT (customer_id), purchase_amount FROM mytable
WHERE discount_applied ='Yes' AND purchase_amount >=(SELECT AVG(purchase_amount) FROM mytable);

-- Top 5 products with the highest average review rating
SELECT item_purchased, ROUND(AVG(review_rating),2) as "AVG Prod Rating" FROM mytable 
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC 
LIMIT 5;

-- Compare the average purchase amount between Standard & Express Shipping
SELECT shipping_type, ROUND(AVG(purchase_amount),2) FROM mytable
WHERE shipping_type in ('Standard','Express')
GROUP BY shipping_type;

-- Do subscribed customers spend more? Compare avg spend & total revenue between subscriber and non - subscriber.
SELECT subscription_status as Customer_Type, COUNT(customer_id) as "Total customer",
ROUND(AVG(purchase_amount),2) as "AVG Spend", 
SUM(purchase_amount) as "Total Revenue" FROM mytable 
GROUP BY subscription_status;

-- 5 products with highest % of purchased with discount applied
SELECT item_purchased, ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/ COUNT(*), 2) as Discount_rate
FROM mytable GROUP BY item_purchased ORDER BY discount_rate DESC LIMIT 5;

-- Segment customers into New, Returning, and Loyal based on their total their num of prev purchase, and show th count of each segment.
WITH customer_type as (
SELECT customer_id, previous_purchases,
CASE
	WHEN previous_purchases = 1 THEN 'NEW'
    WHEN  previous_purchases BETWEEN 2 and 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
 FROM mytable   
)

SELECT customer_segment, COUNT(*) as "Num of Customers"
FROM customer_type
group by customer_segment;

-- Top 3 most purchased product from each category
WITH item_counts as (
SELECT category, item_purchased, COUNT(customer_id) as Total_Orders,
ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) as item_rank
FROM mytable
GROUP BY category, item_purchased
)

SELECT item_rank, category, item_purchased, total_orders
FROM item_counts WHERE item_rank <= 3;

-- Customers who are repeat buyers (more the 5 prev purchases) are also likely to subscribe?
SELECT subscription_status, COUNT(customer_id) AS repeat_buyers FROM mytable
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- What is the revenue contribution of each age group?
SELECT age_group ,SUM(purchase_amount) AS total_revenue FROM mytable
GROUP BY age_group ORDER BY total_revenue DESC;